### ISSUE TITLE
Version 6.3.1 from TER crashes

### ISSUE THREAD

**Issue by Kephson** [manuelselbach/static_info_tables_ru#1]
Update via TER crashes the extension manager because the dependency to static_info_tables fails.

**Comment by manuelselbach** [comment]
Which TYPO3 Version do you use? Do you have static_info_tables installed before?

**Comment by Kephson** [comment]
Hi, sorry for no information.
TYPO3 6.2.26, PHP 5.4 and 5.6.
static_info_tables is installed and I only updated the static_info_tables_ru to the newest version.
Why is only TYPO3 7.6.\* required in your composer file?
https://github.com/manuelselbach/static_info_tables_ru/blob/master/composer.json#L28

**Comment by manuelselbach** [comment]
I only require TYPO3 in version 7.6.\* because a clean installation via composer was reported with this version. It´s no problem to update the version for a range from 6.2 - 7.6, if you prefer an installation of TYPO3 6.2 via composer and it´s needed here.

**Comment by Kephson** [comment]
ok, but after update from 6.3.0 to version 6.3.1 the extension manager still fails because of depedency to static_info_tables (update via extension manager and not via composer)

**Comment by manuelselbach** [comment]
I´m working on that.

**Comment by manuelselbach** [comment]
The Problem seems to be inside the core or within the static_info_tables extension itself.

The extension `static_info_tables` gets removed from the packages and as I require it as dependency, it fails.

Within the composer.json of the extension `static_info_tables` has to be added this snippet:

```
"extra": {
    "typo3/cms": {
      "cms-package-dir": "{$vendor-dir}/typo3/cms",
      "web-dir": ".Build/Web",
      "Package": {
        "partOfMinimalUsableSystem": true
      }
    }
  }
```

EDIT:
This part is what creates the error, but it is placed within this extension. Will be removed in a second and a new Version will be available soon.

And everything works fine. Will try to force a pull request here.

To get ride of the error faster, just remove the composer.json of the extension `static_info_tables_ru`

**Comment by Kephson** [comment]
Thanks a lot for your work!

**Comment by manuelselbach** [comment]
Summary here:

Within the composer.json of the extension `static_info_tables_ru` this snippet was the problem:

```
"extra": {
    "typo3/cms": {
      "Package": {
        "partOfMinimalUsableSystem": true
      }
    }
  }
```

removed in Version 6.3.2
